# Generated by Django 5.1 on 2024-10-15 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_photo', models.ImageField(upload_to='license_photos/')),
                ('rc_book_photo', models.ImageField(upload_to='rc_book_photos/')),
                ('status', models.CharField(choices=[('offline', 'Offline'), ('available', 'Available'), ('on_route', 'On Route')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
